"""Identity value objects.

Identifiers are *supplied* to the domain rather than generated by it: the token
comes from a ``RandomPort``/``ClockPort`` adapter so every run can be made
deterministic under test.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import ClassVar

from creative_brain.domain.exceptions import DomainRuleViolation

_TOKEN = re.compile(r"^[a-z0-9]{4,32}$")


@dataclass(frozen=True, slots=True, order=True)
class EntityId:
    """A prefixed, human-readable identifier such as ``concept_7f3ac21b``."""

    prefix: ClassVar[str] = "entity"

    value: str

    def __post_init__(self) -> None:
        if not self.value.startswith(f"{type(self).prefix}_"):
            raise DomainRuleViolation(
                f"identifier '{self.value}' must start with '{type(self).prefix}_'"
            )
        token = self.value.split("_", 1)[1]
        if not _TOKEN.match(token):
            raise DomainRuleViolation(f"identifier token '{token}' is not a 4-32 char [a-z0-9] slug")

    @classmethod
    def from_token(cls, token: str) -> EntityId:
        """Build an identifier from a raw token produced by a randomness adapter."""
        return cls(f"{cls.prefix}_{token}")

    def __str__(self) -> str:
        return self.value


class ObservationId(EntityId):
    """Identifies a captured signal from the world."""

    prefix: ClassVar[str] = "obs"


class QuestionId(EntityId):
    """Identifies a creative question."""

    prefix: ClassVar[str] = "question"


class SeedId(EntityId):
    """Identifies a raw creative seed."""

    prefix: ClassVar[str] = "seed"


class ConceptId(EntityId):
    """Identifies a creative concept as it walks the lifecycle."""

    prefix: ClassVar[str] = "concept"


class ProjectId(EntityId):
    """Identifies an approved creative project."""

    prefix: ClassVar[str] = "project"


class TournamentId(EntityId):
    """Identifies one run of the creative tournament."""

    prefix: ClassVar[str] = "tournament"


class CycleId(EntityId):
    """Identifies one full circadian cycle."""

    prefix: ClassVar[str] = "cycle"


class MemoryId(EntityId):
    """Identifies a persisted memory record."""

    prefix: ClassVar[str] = "mem"


class DreamId(EntityId):
    """Identifies a dream session."""

    prefix: ClassVar[str] = "dream"


class FindingId(EntityId):
    """Identifies a research finding."""

    prefix: ClassVar[str] = "finding"


class SessionId(EntityId):
    """Identifies a runtime session (one process lifetime)."""

    prefix: ClassVar[str] = "session"
